# Generated by Django 2.0 on 2019-04-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0002_auto_20190423_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
